---
processes:
- name: calico
  executable: /var/vcap/jobs/calico/bin/calico_ctl
  args: []
  ephemeral_disk: true
  persistent_disk: false

  limits:
    memory: 1G
    open_files: 1024

# examples/docs at:
# - https://github.com/cloudfoundry-incubator/bpm-release/blob/master/jobs/test-server/templates/bpm.yml.erb
# - https://github.com/cloudfoundry-incubator/bpm-release/tree/master/docs
